inherits = "gruvbox_dark_hard"

# Override the theming for "keyword"s:
#"keyword" = { fg = "gold" }

# Override colors in the palette:
#[palette]
#berry = "#2A2A4D"

"ui.text.focus" = { fg = "yellow0" }
